#!/bin/bash

app=${1%%.git}

#expand the code into the app directory
echo "working dir:" `pwd -P`
echo "application: $app"
echo "repository: $1"
echo "revision: $2"
echo "username: $3"
echo "fingerprint: $4"

## Exit if there is no revision to support branch deletion
if [[ "$2" == "0000000000000000000000000000000000000000" ]]; then
    echo "----> No revision to deploy."
    exit
fi

## Deploy code
echo "----> Deploying code to /srv/app/$app/$2 ..."
mkdir -p "/srv/app/$app/$2" && cat | tar -x -C "/srv/app/$app/$2"
echo "----> Linking current -> $2 ..."
ln -s -T -f "$2" "/srv/app/$app/current"

